import Link from "next/link";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

// ── Review agenda preview data ────────────────────────────────────────────────

const PREVIEW_ITEMS = [
  {
    rank: 1,
    time: "14:32",
    label: "fight" as const,
    title: "Baron pit 4v4",
    context: "−3 kills, 2 ults spent on engage",
    coaching: "Engaged before Aatrox ult came back up. Walk through ult timing.",
  },
  {
    rank: 2,
    time: "22:15",
    label: "objective" as const,
    title: "Soul + Nashor exchange",
    context: "Net −1200g, both objectives ceded",
    coaching: "Soul stack sold the initiation. Baron denial should have been priority.",
  },
  {
    rank: 3,
    time: "08:47",
    label: "lane" as const,
    title: "Top 1200g behind at 8m",
    context: "+18 CS gap, no jungle presence top",
    coaching: "No counter-gank response. Top diff grew uncontested for four minutes.",
  },
];

const LABEL_STYLE: Record<typeof PREVIEW_ITEMS[number]["label"], string> = {
  fight:     "text-orange-400 border-orange-500/30 bg-orange-500/8",
  objective: "text-violet-400 border-violet-500/30 bg-violet-500/8",
  lane:      "text-cyan-400  border-cyan-500/30  bg-cyan-500/8",
};

// ── How it works steps ────────────────────────────────────────────────────────

const STEPS = [
  {
    n: "01",
    title: "Import",
    body: "Connect your Riot account or supply GRID JSONL exports. The engine handles match ingestion and parsing.",
  },
  {
    n: "02",
    title: "Analyze",
    body: "Gold differentials, fight quality, objective trades, and lane states at three checkpoints — computed locally, no cloud.",
  },
  {
    n: "03",
    title: "Debrief",
    body: "A ranked review agenda: 6 to 8 timestamped moments, each with context and a coaching cue, generated by a local AI model.",
  },
];

// ── Sub-components ────────────────────────────────────────────────────────────

function ReviewPreview() {
  return (
    <div
      className="rounded-lg border border-border bg-card overflow-hidden animate-fade-in"
      style={{ animationDelay: "320ms" }}
    >
      {/* Terminal-style header bar */}
      <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
        <span className="font-mono text-xs text-muted-foreground">
          game_23.rofl · review agenda
        </span>
        <span className="font-mono text-xs text-primary">7 items</span>
      </div>

      {/* Agenda items */}
      <div className="divide-y divide-border">
        {PREVIEW_ITEMS.map((item) => (
          <div key={item.rank} className="flex gap-3 px-4 py-3.5">
            <span className="mt-0.5 w-4 shrink-0 font-mono text-xs text-muted-foreground/50">
              {item.rank}
            </span>
            <div className="min-w-0 flex-1">
              {/* Meta row */}
              <div className="mb-1 flex flex-wrap items-center gap-2">
                <span className="font-mono text-xs text-primary">{item.time}</span>
                <span
                  className={cn(
                    "rounded-sm border px-1.5 py-px font-mono text-xs",
                    LABEL_STYLE[item.label]
                  )}
                >
                  {item.label}
                </span>
                <span className="text-sm font-medium text-foreground">{item.title}</span>
              </div>
              {/* Data line */}
              <p className="font-mono text-xs text-muted-foreground">{item.context}</p>
              {/* Coaching cue */}
              <p className="mt-0.5 text-xs leading-relaxed text-foreground/65">
                {item.coaching}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Footer hint */}
      <div className="border-t border-border px-4 py-2.5">
        <span className="font-mono text-xs text-muted-foreground/50">
          showing 3 of 7 · sorted by impact
        </span>
      </div>
    </div>
  );
}

function HowItWorks() {
  return (
    <div className="grid gap-12 sm:grid-cols-3">
      {STEPS.map((step) => (
        <div key={step.n} className="space-y-3">
          {/* Large structural number — low-opacity amber, not a decoration */}
          <span className="block font-mono text-5xl font-extrabold leading-none text-primary/25">
            {step.n}
          </span>
          <h3 className="text-base font-semibold text-foreground">{step.title}</h3>
          <p className="text-sm leading-relaxed text-muted-foreground">{step.body}</p>
        </div>
      ))}
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function LandingPage() {
  return (
    <div>
      {/* ── Hero ── */}
      <section className="relative flex min-h-[calc(100vh-3.5rem)] items-center">
        <div className="mx-auto grid w-full max-w-screen-xl grid-cols-1 items-center gap-12 px-6 py-20 lg:grid-cols-[1fr_460px] xl:gap-20">

          {/* Left: headline + CTA */}
          <div>
            <h1
              className="font-display font-extrabold tracking-tight text-foreground animate-fade-in"
              style={{ fontSize: "clamp(2.75rem, 6vw, 4.75rem)", lineHeight: 1.08 }}
            >
              Hours of replay.<br />
              Six moments.
            </h1>

            <p
              className="mt-6 max-w-sm text-base leading-relaxed text-muted-foreground animate-fade-in"
              style={{ animationDelay: "100ms" }}
            >
              AnalizeLeague builds the post-game review agenda automatically: fights, objective trades, lane states — ranked by impact, with timestamps.
            </p>

            <div
              className="mt-8 flex flex-wrap items-center gap-4 animate-fade-in"
              style={{ animationDelay: "200ms" }}
            >
              <Button size="lg" asChild>
                <Link href="/app">Open App</Link>
              </Button>
              <span className="text-xs text-muted-foreground">
                No cloud. No account. Runs locally.
              </span>
            </div>
          </div>

          {/* Right: live agenda preview */}
          <ReviewPreview />
        </div>
      </section>

      {/* ── How it works ── */}
      <section className="border-t border-border py-24">
        <div className="mx-auto max-w-screen-xl px-6">
          <p className="mb-14 text-xs uppercase tracking-widest text-muted-foreground">
            How it works
          </p>
          <HowItWorks />
        </div>
      </section>

      {/* ── Local-first note ── */}
      <section className="border-t border-border py-16">
        <div className="mx-auto max-w-screen-xl px-6">
          <p className="max-w-xl text-sm leading-relaxed text-muted-foreground">
            <span className="font-medium text-foreground">Scrim data stays on your machine.</span>{" "}
            The analysis model runs locally via Ollama. No external API calls, no telemetry, no exposure of proprietary team strategy.
          </p>
        </div>
      </section>

      {/* ── Final CTA ── */}
      <section className="border-t border-border py-24">
        <div className="mx-auto max-w-screen-xl px-6">
          <div className="max-w-md">
            <h2 className="font-display font-bold tracking-tight text-foreground" style={{ fontSize: "clamp(1.5rem, 3vw, 2rem)" }}>
              Ready to run your first debrief?
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
              Paste your Riot ID, point it at your Ollama instance, and get a review agenda in under a minute.
            </p>
            <div className="mt-8">
              <Button size="lg" asChild>
                <Link href="/app">Open App</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
