"""
API route handlers — Phase 2 implementation.

Endpoints consumed by the frontend (lib/api.ts):
  GET  /games                — game selector list
  GET  /games/{id}/digest    — full GameDigest for the detail view
  GET  /games/{id}/agenda    — LLM-generated ranked review agenda
  POST /ask                  — natural-language Q&A over scrim history

Legacy stubs kept for reference:
  POST /debrief              — original endpoint (now superseded)
  POST /query                — original endpoint (now superseded)
"""

from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, HTTPException, Path, Request
from pydantic import BaseModel, Field

from app.digest.models import GameDigest
from app.llm.agent import AgendaItem, QAResponse, answer_question, generate_agenda
from app.storage.db import get_agenda, get_game, list_games, save_agenda

logger = logging.getLogger(__name__)

router = APIRouter()

# Riot match-v5 IDs look like "EUW1_6900000000"; test fixtures use "EUW1_TEST123".
_GAME_ID_PATTERN = r"^[A-Z]{2,4}\d{1,3}_[A-Z0-9]+$"
GameIdPath = Path(..., pattern=_GAME_ID_PATTERN, description="Riot match ID, e.g. EUW1_6900000000")


# ── Request / response models ─────────────────────────────────────────────────


class AskRequest(BaseModel):
    question: str = Field(min_length=1, max_length=2000)


# ── Helpers ───────────────────────────────────────────────────────────────────


def _db(request: Request) -> Any:  # noqa: ANN401 — returns duckdb.DuckDBPyConnection
    return request.app.state.db


# ── Game selector ─────────────────────────────────────────────────────────────


@router.get("/games", response_model=list[dict[str, Any]])
async def get_games(request: Request) -> list[dict[str, Any]]:
    """Return summary list of all stored games for the game selector UI."""
    return list_games(_db(request))


# ── Game detail ───────────────────────────────────────────────────────────────


@router.get("/games/{game_id}/digest", response_model=GameDigest)
async def get_game_digest(request: Request, game_id: str = GameIdPath) -> GameDigest:
    """Return the full GameDigest for a stored game."""
    digest = get_game(_db(request), game_id)
    if digest is None:
        raise HTTPException(
            status_code=404,
            detail=f"Game '{game_id}' not found. Run the seed script first.",
        )
    return digest


# ── Agenda (LLM) ──────────────────────────────────────────────────────────────


@router.get("/games/{game_id}/agenda", response_model=list[AgendaItem])
async def get_game_agenda(request: Request, game_id: str = GameIdPath) -> list[AgendaItem]:
    """
    Return the ranked review agenda for a game.

    Generated by the local Ollama model on first call; cached in DuckDB
    on subsequent calls to avoid repeated inference.
    """
    db = _db(request)

    # Check cache
    cached = get_agenda(db, game_id)
    if cached is not None:
        return [AgendaItem.model_validate(item) for item in cached]

    digest = get_game(db, game_id)
    if digest is None:
        raise HTTPException(
            status_code=404,
            detail=f"Game '{game_id}' not found. Run the seed script first.",
        )

    agenda = await generate_agenda(digest)

    # Cache for future calls
    save_agenda(db, game_id, [item.model_dump() for item in agenda])

    return agenda


# ── Q&A ───────────────────────────────────────────────────────────────────────


@router.post("/ask", response_model=QAResponse)
async def ask(body: AskRequest, request: Request) -> QAResponse:
    """
    Answer a natural-language question over all stored scrim data.

    Routes through the two-stage text-to-SQL pipeline: the model proposes a
    SELECT against the derived DuckDB tables, the validator (app/llm/sql.py)
    enforces a whitelist + safe-keyword rules, and the rows are then narrated.
    """
    return await answer_question(body.question, _db(request))


# ── Legacy endpoints (kept for compatibility) ─────────────────────────────────


class DebriefRequest(BaseModel):
    game_id: str
    data_source: str = "riot"


class DebriefResponse(BaseModel):
    game_id: str
    debrief: str


class QueryRequest(BaseModel):
    game_id: str
    question: str


class QueryResponse(BaseModel):
    game_id: str
    answer: str


@router.post("/debrief", response_model=DebriefResponse, deprecated=True)
async def post_debrief(body: DebriefRequest, request: Request) -> DebriefResponse:
    """Deprecated — use GET /games/{id}/agenda instead."""
    db = _db(request)
    digest = get_game(db, body.game_id)
    if digest is None:
        raise HTTPException(status_code=404, detail=f"Game '{body.game_id}' not found.")
    agenda = await generate_agenda(digest)
    debrief_text = "\n\n".join(
        f"[{i.rank}] {i.title} (t={i.t}s)\n{i.context}\nWatch: {i.what_to_watch}" for i in agenda
    )
    return DebriefResponse(game_id=body.game_id, debrief=debrief_text)


@router.post("/query", response_model=QueryResponse, deprecated=True)
async def post_query(body: QueryRequest, request: Request) -> QueryResponse:
    """Deprecated — use POST /ask instead."""
    qa = await answer_question(body.question, _db(request))
    return QueryResponse(game_id=body.game_id, answer=qa.answer)
