"""
LLM agent using Ollama for local inference.

Privacy guarantee: this module sends ONLY the GameDigest JSON to Ollama,
which runs entirely on the local machine. Raw game data and player
identities are never transmitted to any external service.

The LLM role is narration only — all quantitative analysis was already
done by build_digest(). See /.ai/architecture.md for the design rationale.
"""
from __future__ import annotations

import logging

from app.config import settings
from app.digest.models import GameDigest

logger = logging.getLogger(__name__)


async def generate_debrief(digest: GameDigest) -> str:
    """
    Generate a natural-language post-game debrief from a GameDigest.

    The output is a ranked "review agenda" of the 6–8 moments that matter,
    each with a timestamp and a description of what to look for.

    Args:
        digest: Compact game digest (all calculations done in Python, not by LLM).

    Returns:
        Structured prose debrief generated by the local Ollama model.

    Raises:
        NotImplementedError: Phase 1 stub. Implement in Phase 2.
    """
    # TODO (Phase 2): build a structured prompt from digest.model_dump_json()
    # and call ollama.AsyncClient(host=settings.ollama_host).chat(
    #     model=settings.ollama_model, messages=[{"role": "user", "content": prompt}]
    # )
    raise NotImplementedError(
        "generate_debrief is a Phase 1 stub. Implement in Phase 2."
    )


async def answer_query(digest: GameDigest, question: str) -> str:
    """
    Answer a natural-language question about a specific game.

    Args:
        digest:   The game digest to reason over.
        question: Free-text question from the analyst or coach.

    Returns:
        Focused prose answer generated by the local Ollama model.

    Raises:
        NotImplementedError: Phase 1 stub. Implement in Phase 2.
    """
    # TODO (Phase 2): construct a QA prompt combining digest + question,
    # stream the response from ollama.AsyncClient if latency is a concern.
    _ = settings  # used in Phase 2 for ollama_host / ollama_model
    raise NotImplementedError(
        "answer_query is a Phase 1 stub. Implement in Phase 2."
    )
